### ISSUE TITLE
CKEditor With special Symbol

### ISSUE THREAD

**Issue by vishaldeshai** [insanoid/iOS-HTMLTextEditor#6]
Hello,

When my text is containing Character ' then it return error like " 'content goes here. replaced on webviewdidload:' "

Thanks in advance.
Vishal

**Comment by insanoid** [comment]
it's not the fault of CKEditor or the code; it's because you are setting it up wrong:

`[_webView stringByEvaluatingJavaScriptFromString:@"document.getElementById('editor').innerHTML='<b>'Hello</b> <i>World</i>!';"];`

`'` should be converted to HTML encoding before you  put it there:

`<b>&#39;Hello…` for `'Hello…".
